---
functional:
  - Возможность зарегистрировать нового пользователя
  - Возможность авторизации с помощью email и password
  - Возможность установить фотографию пользователя в личном кабинете
  - Возможность просмотреть список активных игр в lobby
  - Возможность просмотреть список турниров
  - В списке турниров отображаются активные турниры
  - В списке турниров отображаются завершенные турниры
  - Возможность просмотреть список завершенных игр
  - Возможность вызвать форму для создания новой игры
  - Возможность выбрать уровень сложности в форме создания новой игры
  - Возможность выбрать тип игры в форме создания новой игры
  - Возможность задать длительность игры в форме создания новой игры
  - Возможность выбрать игру по имени в форме создания новой игры
  - Возможность создать новую игру, заполнив форму для создания новой игры
  
non-functional:
  - Отображается изображение с надписью No Photo в профиле пользователя без фотографии
  - Отображается заголовок My profile на странице информации о профиле пользователя
  - Рейтинг пользователей отображается в виде таблицы
  - Рядом с именем пользователя отображается зеленый кружок, когда пользователь онлайн
  - Кнопка создания новой игры зеленого цвета
  - Надпись Create A Game расположена по центру в кнопке создания новой игры
  - Надписи внутри приложения выполнены одним типом шрифта
  
implicit:
  - Взаимодействие приложения с базой данных происходит по принципу "Клиент - Сервер"
  - Пользователи не могут изменять автотесты внутри игр
  - Пользователь не может вносить изменения в личную информацию другого пользователя
